version: '3.8'

services:
  python-module:
    build:
      context: /home/lucas/Documentos/GitHub/trabalhoSD
      dockerfile: python.Dockerfile
    container_name: python-container
    volumes:
      - /home/lucas/Documentos/GitHub/trabalhoSD:/app
    command: python data_cleaning.py
    depends_on:
      - node-module

  node-module:
    build:
      context: /home/lucas/Documentos/GitHub/trabalhoSD
      dockerfile: node.Dockerfile
    container_name: node-container
    ports:
      - "3000:3000"
    volumes:
      - /home/lucas/Documentos/GitHub/trabalhoSD:/app
    environment:
      - NODE_ENV=development
