FROM python:3.11

WORKDIR /app

# Copie o requirements.txt
COPY /requirements.txt /app

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copie os scripts Python
COPY ./ /app
#COPY /home/lucas/Documentos/GitHub/trabalhoSD/generate_graph.py /app/

CMD ["python", "data_cleaning.py"]
